#!/bin/sh

job_home=`pwd -P`
export HOME="/afs/cern.ch/exp/totem/scratch/jkaspar"
export RFIO_USE_CASTOR_V2=YES
export STAGE_HOST=castorpublic
export STAGE_SVCCLASS=default
export SCRAM_ARCH='slc5_amd64_gcc434'
source "/afs/cern.ch/cms/cmsset_default.sh"
cd "/afs/cern.ch/work/j/jkaspar/software/offline/704/src"
eval `scram runtime -sh`

# EOS configuration
source "/afs/cern.ch/project/eos/installation/totem/etc/setup.sh"
shopt -s expand_aliases

# note: $dir, $dgn, $tag will be string-replaced by sed when making scripts

function SafeCmd()
{
	echo ""
	echo ">> SafeCmd: $@"
	for i in {1..10}
	do
		echo "* attempt $i:"
		"$@" && return 0
		sleep 5
	done
	echo "* giving up..."
	return 1
}

# define directories
anal_dir="/afs/cern.ch/work/j/jkaspar/analyses/elastic/6500GeV,beta90,10sigma"
block_dir="$anal_dir/$dir"
job_dir="$job_home"
storage_dir="/eos/totem/user/j/jkaspar/analyses/elastic/6500GeV,beta90,10sigma/$dir"

(

# run the process
cd "$job_home"

"${block_dir}/.distill" "$dgn"\
	&> "${block_dir}/distill_$dgn.log_run"

ls -l

# copy files
eos cp "${block_dir}/distill_$dgn.log_run" "$storage_dir/"
eos cp "distill_$dgn_new.root" "$storage_dir/"

) &> "$block_dir/distill_$dgn.log_job"
