#!/bin/bash

#----------------------------------------------------------------------------------------------------
# defaults

batch_queue="1nd"
batch_resources=""
batch_options=""

#----------------------------------------------------------------------------------------------------

function Submit()
{
	local dir="$1"
	local tag="${dir//\//_}"

	echo ""
	echo "* $dir"

	# compile
	cd "../../" || return 1
	./run distill.cc -dno -no-bckg "$dir" || return 2
	cd - &> /dev/null

	# process each diagonal
	#for dgn in "45b_56t" "45t_56b"
	for dgn in "45b_56b" "45t_56t"
	do
		# make job script
		local job_file="run/job_distill_${tag}_${dgn}"
		echo "$job_file"

		cat "job_template" | sed "\
				s|\$dir|$dir|g;\
				s|\$dgn|$dgn|g;\
				s|\$tag|$tag|g;\
			" > "$job_file"

		# submit
		chmod a+x "$job_file"
		bsub -q "$batch_queue" -R "$batch_resources" $batch_options "`pwd`/$job_file"
	done
}
